checkpoint:
  chkpt_saving_period        : 1
  preempt_chkpt_saving_period: 1
  directory                  : experiments/chkpts
  prefix                     : fsdp
  path_chkpt_prev            : null
  pretrain                   : null
dataset:
  batch_size     : 2
  num_workers    : 2
  path_train     : experiments/datasets/test.json
  path_eval      : experiments/datasets/test.json
  seg_size       : 20
  entry_per_cycle: 1
  debug          : false
  server_address : [localhost, 5000]
  transforms:
    #norm: {'Rayonix': {'mean': 116.92, 'std': 22.89}, 'epix10k2M': {'mean': 46.6, 'std': 98.3}, 'jungfrau4M': {'mean': 593.17, 'std': 204.13}} # added 5/10
    norm:
      Rayonix:
        mean: 116.92
        std: 22.89
      epix10k2M:
        mean: 46.6
        std: 98.3
      jungfrau4M:
        mean: 593.17
        std: 204.13
    H_pad: 2048
    W_pad: 2048
    num_patch: 100
    size_patch: 20
    angle_max: 360
    frac_shift_max: 0.1
    downscale_factors: [2, 2]
    var_size_patch: 0.2
    patch_size: 224
    stride: 224
dist:
  backend               : nccl
  uses_unique_world_seed: true
  dtype                 : float16
logging:
  directory : experiments/logs
  prefix    : fsdp
  level     : debug
loss:
  grad_accum_steps: 10
lr_scheduler:
  min_lr                : !!float 1e-7
  total_iterations      : !!int 1_000_000
  uses_prev             : true
  warmup_iterations     : 5
  scheduler_step_period : 20
misc:
  max_epochs          : 5
  max_eval_iter       : 50
  max_eval_retry      : 2
  num_gpus            : 4
  uses_mixed_precision: true
  compiles_model      : false
  data_dump_on        : false
model:
  name: 'facebook/vit-mae-base'
  mask_ratio: 0.75
optim:
  grad_clip   : 1.0
  lr          : !!float 2e-4
  weight_decay: !!float 1e-4
